### ISSUE TITLE
Error accessing the web application - 405 Method not allowed - XHR POST http://localhost:1234/paraview/ 

### ISSUE THREAD

**Issue by topcat** [Kitware/vtk-web-solutions#2]
Hello,

First, I really love Trame and VTK, so thank you for the awesome work you guys have put in :slight_smile:

I am evaluating using Trame as just the backend with a ReactJs frontend for some medical visualization and I came across this example.

I have cloned this repo and followed the steps in the README found in the simple-server directory. I haven’t built anything in the client-server directory, do I need to?

On running the app in the simple-server directory and attempting to access it in my browser, nothing shows up and if I inspect the developer tools of my browser, I see the following error in the console :

XHR POST http://localhost:1234/paraview/
[HTTP/1.1 405 Method Not Allowed 1ms]

POST
http://localhost:1234/paraview/
Status
405
Method Not Allowed
VersionHTTP/1.1
Transferred208 B (23 B size)
Referrer Policystrict-origin-when-cross-origin

I am quite new to Trame / VTK / Paraview so I can’t make sense of how I should go about debugging this. Would sincerely appreciate any pointers.

Thank you.

Regards,
Jeetu

**Comment by jourdain** [comment]
Good catch! To fix it, you can just run `pip install -U "trame<3.6"`.

The reason for that is `trame>=3.6` is using `wslink>=2`, while the react client in that code base uses `wslink<2`.
So with the current JS code, you need to use  `trame<3.6`. But if you update the client to pick the latest wslink, it should just work with the latest trame.

**Comment by topcat** [comment]
And it worked :) 

Thank you so much Sebastien :) works like a charm now. Appreciate your help :)
