### ISSUE TITLE
Please provide example that uses VTK python wrapping 

### ISSUE THREAD

**Issue by jspanchu** [Kitware/vtk-web-solutions#4]
In order to lower the bar for users to try these examples, we can remove pybind11 dependency from the cxx-engine examples and use inbuilt VTK python wrapping generator from the VTK CMake module API.

**Comment by jourdain** [comment]
That repo has 2 examples:
1. With custom C++ code where we show binding and python + trame integration.
2. With just standard server and just the client code for react

**Comment by jspanchu** [comment]
The request is to modify the first example. It uses `pybind11 `which doesn't work when users have classes derived from VTK object. It will work when the cmake uses `vtk_module_add_module` instead of `pybind11_add_module`.

I've a developer interested to know how they can instantiate their subclasses of VTK C++ classes in python and use trame.

**Comment by jourdain** [comment]
Then we need a third example/directory, because, the pybind path is interesting to keep and have. But David T. provided a SuperBuild to properly build all the required pieces. But never got the chance to properly document and expose it here in that repo.

**Comment by jspanchu** [comment]
Okay. Fair enough. Looks like some renaming is in order then. My suggestion:
1. `client-server` -> `client-server-cxx-pybind11`
2. new `client-server-cxx` (self explainatory, need nothing else beside trame, VTK and tools to build it)

**Comment by jourdain** [comment]
1. `client-server-cxx-pybind11`
2. `client-server-sdk`

**Comment by jourdain** [comment]
I don't really know for 2, but since you mentioned the vtk-sdk, I think we should put it in the name
