### ISSUE TITLE
Can the VTK wheel sdk be used instead of building VTK from source?

### ISSUE THREAD

**Issue by jspanchu** [Kitware/vtk-web-solutions#5]

**Comment by jourdain** [comment]
Already the case

**Comment by jspanchu** [comment]
Are they documented somewhere? These instructions ask to build entire VTK from source https://github.com/Kitware/vtk-web-solutions/blob/master/client-server/cxx-engine/README.md#vtk

**Comment by jourdain** [comment]
Right there https://github.com/Kitware/vtk-web-solutions/tree/master/simple-server

**Comment by jourdain** [comment]
This directory https://github.com/Kitware/vtk-web-solutions/tree/master/client-server could/should be renamed `custom-cxx-server-with-vtk-and-vue-react-clients-example`

**Comment by jspanchu** [comment]
Nope, that's not what I'm looking for. The simple-server example pip installs vtk and it is in pure python.

I'm asking if we can use the `vtk-wheel-sdk` (not `vtk`) published on vtk.org/downloads. That SDK has headers and cmake files, so a developer looking to test waters doesn't have to sit around waiting for VTK to configure and build.

**Comment by jspanchu** [comment]
For example, here's the sdk for macos-arm64 https://www.vtk.org/files/release/9.3/vtk-wheel-sdk-9.3.0-cp311-cp311-macosx_11_0_arm64.tar.xz

**Comment by jourdain** [comment]
Then we need a 3rd directory that provide the sdk route.
